# Generated by Django 4.0.5 on 2022-07-15 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='thetracker.job'),
        ),
    ]
