# Generated by Django 4.0.5 on 2022-07-15 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thetracker', '0002_alter_memo_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoWriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='memo',
            name='memo_writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thetracker.memowriter'),
        ),
    ]
